/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-08-29 04:48:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\" class=\"no-js\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"canonical\" href=\"https://html5-templates.com/\" />\n");
      out.write("    <title>Responsive HTML5 Page Layout Template</title>\n");
      out.write("    <meta name=\"description\" content=\"Simple HTML5 Page layout template with header, footer, sidebar etc.\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets\\css\\stylesheet.css\">\n");
      out.write("    <script src=\"script.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		<div id=\"logo\"><img src=\"assets/images/13-BulldogFullColor.png\">Week 1 Assignment</div>\n");
      out.write("		<nav>  \n");
      out.write("			<ul>\n");
      out.write("				<li><a href=\"index.jsp\">Home</a>\n");
      out.write("				<li><a href=\"about.jsp\">About Us</a>\n");
      out.write("				<li><a href=\"contact.jsp\">Contact Us</a>\n");
      out.write("			</ul>\n");
      out.write("		</nav>\n");
      out.write("	</header>\n");
      out.write("	<section>\n");
      out.write("		<strong>Demonstration of a simple page layout using HTML5 tags: header, nav, section, main, article, aside, footer, address.</strong>\n");
      out.write("	</section>\n");
      out.write("	<section id=\"pageContent\">\n");
      out.write("		<main role=\"main\">\n");
      out.write("			<article>\n");
      out.write("				<h2>HTML Lists</h2>\n");
      out.write("				<ul>\n");
      out.write("				    <li>Week 1</li>\n");
      out.write("				    <li>Week 2</li>\n");
      out.write("				    <li>Week 3</li>\n");
      out.write("				</ul>\n");
      out.write("			</article>\n");
      out.write("			<article>\n");
      out.write("				<h2>HTML Tables</h2>\n");
      out.write("				<table>\n");
      out.write("				    <tr>\n");
      out.write("				        <th scope=\"col\">First Name</th>\n");
      out.write("				        <th scope=\"col\">Last Name</th>\n");
      out.write("				        <th scope=\"col\">Age</th>\n");
      out.write("				    </tr>\n");
      out.write("				    <tr>\n");
      out.write("				        <td>Jill</td>\n");
      out.write("				        <td>Smith</td>\n");
      out.write("				        <td>50</td>\n");
      out.write("				    </tr>\n");
      out.write("				    <tr>\n");
      out.write("				        <td>Eve</td>\n");
      out.write("				        <td>Jackson</td>\n");
      out.write("				        <td>94</td>\n");
      out.write("				    </tr>\n");
      out.write("				</table>\n");
      out.write("			</article>\n");
      out.write("			<article>\n");
      out.write("				<h2>Ex ignota epicurei quo</h2>\n");
      out.write("				<p>Quo debet vivendo ex. Qui ut admodum senserit partiendo. Id adipiscing disputando eam, sea id magna pertinax concludaturque. Ex ignota epicurei quo, his ex doctus delenit fabellas, erat timeam cotidieque sit in. Vel eu soleat voluptatibus, cum cu exerci mediocritatem. Malis legere at per, has brute putant animal et, in consul utamur usu.</p>\n");
      out.write("			</article>\n");
      out.write("			<article>\n");
      out.write("				<h2>His at autem inani volutpat</h2>\n");
      out.write("				<p>Te has amet modo perfecto, te eum mucius conclusionemque, mel te erat deterruisset. Duo ceteros phaedrum id, ornatus postulant in sea. His at autem inani volutpat. Tollit possit in pri, platonem persecuti ad vix, vel nisl albucius gloriatur no.</p>\n");
      out.write("			</article>\n");
      out.write("		</main>\n");
      out.write("		<aside>\n");
      out.write("			<div>Announcements</div>\n");
      out.write("			<div>Sidebar 2</div>\n");
      out.write("			<div>Sidebar 3</div>\n");
      out.write("		</aside>\n");
      out.write("	</section>\n");
      out.write("	<footer>\n");
      out.write("		<p>&copy; You can copy, edit and publish this template but please leave a link to our website | <a href=\"https://html5-templates.com/\" target=\"_blank\" rel=\"nofollow\">HTML5 Templates</a></p>\n");
      out.write("		<address>\n");
      out.write("			Contact: <a href=\"mailto:me@example.com\">Mail me</a>\n");
      out.write("		</address>\n");
      out.write("	</footer>\n");
      out.write("\n");
      out.write("<script src=\"assets/js/scripts.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
